"""Add can_post column to user

Revision ID: 14c7d7c27027
Revises: e73e37d576af
Create Date: 2025-05-29 13:41:06.296432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14c7d7c27027'
down_revision = 'e73e37d576af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_post', sa.Boolean(), nullable=True))
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('can_post')

    # ### end Alembic commands ###
