"""Add permissions field

Revision ID: e73e37d576af
Revises: f0b104ce3e10
Create Date: 2025-05-28 22:08:55.975160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e73e37d576af'
down_revision = 'f0b104ce3e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_uid')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    op.create_table('available_uid',
    sa.Column('uid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
